# Generated by Django 3.1.2 on 2020-10-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ALogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=120)),
                ('passwd', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mob', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=120)),
                ('subj', models.CharField(max_length=200)),
                ('msg', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('mob', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=120)),
                ('passwd', models.CharField(max_length=200)),
                ('dt', models.DateField(max_length=50)),
            ],
        ),
    ]
