# Generated by Django 3.1.2 on 2020-10-06 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactModel',
        ),
    ]
