# Generated by Django 3.1.2 on 2020-10-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0003_auto_20201006_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=120)),
                ('pprice', models.CharField(max_length=50)),
                ('ppic', models.FileField(upload_to='static/products/')),
            ],
        ),
    ]
